openapi: 3.0.0
info:
  title: home-iot-api
  description: The API for the EatBacon IOT project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/EladVider/Calculate/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /Login:
    post:
      tags:
      - Login
      summary: Perform login to app
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Errors
      x-swagger-router-controller: Login
  /Calculate:
    post:
      tags:
      - Calculate
      summary: Perform arithmetic operations on two numbers
      operationId: calculate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
        required: true
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      security:
      - bearerAuth: []
      x-swagger-router-controller: Calculate
components:
  schemas:
    Login:
      required:
      - code
      - phone
      type: object
      properties:
        phone:
          type: string
          example: "0547649395"
        code:
          minLength: 5
          type: string
          example: "07584"
    Operator:
      required:
      - num1
      - num2
      - operation
      type: object
      properties:
        num1:
          type: integer
          format: int32
          example: 3
        num2:
          type: integer
          format: int32
          example: 5
        operation:
          type: string
          example: "+"
          enum:
          - "+"
          - "-"
          - '*'
          - /
    inline_response_200:
      type: object
      properties:
        token:
          type: string
          description: JWT token for authentication
      example:
        token: token
    inline_response_200_1:
      type: object
      properties:
        result:
          type: integer
          example: 8
      example:
        result: 8
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
